FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
RUN go install github.com/pufferffish/wireproxy/cmd/wireproxy@v1.0.9

FROM alpine:latest
RUN apk add --no-cache wget
COPY --from=builder /go/bin/wireproxy /usr/local/bin/wireproxy
ENTRYPOINT ["wireproxy"]
